<?php

namespace Ebay\Sell\Inventory\Model;

use OpenAPI\Runtime\AbstractModel;

/**
 * This type is used by the request payload of the
 * <strong>publishByInventoryItemGroup</strong> call. The identifier of the
 * inventory item group to publish and the eBay marketplace where the listing will
 * be published is needed in the request payload.
 */
class PublishByInventoryItemGroupRequest extends AbstractModel
{
    /**
     * This is the unique identifier of the inventory item group. All unpublished
     * offers associated with this inventory item group will be published as a
     * multiple-variation listing if the <strong>publishByInventoryItemGroup</strong>
     * call is successful. The <strong>inventoryItemGroupKey</strong> identifier is
     * automatically generated by eBay once an inventory item group is
     * created.<br/><br/>To retrieve an <strong>inventoryItemGroupKey</strong> value,
     * you can use the <strong>getInventoryItem</strong> call to retrieve an inventory
     * item that is known to be in the inventory item group to publish, and then look
     * for the inventory item group identifier under the <strong>groupIds</strong>
     * container in the response of that call.
     *
     * @var string
     */
    public $inventoryItemGroupKey = null;

    /**
     * This is the unique identifier of the eBay site on which the multiple-variation
     * listing will be published. The <strong>marketPlaceId</strong> enumeration values
     * are found in <strong>MarketplaceIdEnum</strong>. For implementation help, refer
     * to <a
     * href='https://developer.ebay.com/api-docs/sell/inventory/types/slr:MarketplaceEnum'>eBay
     * API documentation</a>.
     *
     * @var string
     */
    public $marketplaceId = null;
}
